theme: jekyll-theme-minimal
title: Vicente's homepage
description: Bookmark this to keep an eye on my project updates!

domain: vicente-iii.github.io       # if you want to force HTTPS, specify the domain without the http at the start, e.g. example.com
url: https://vicente-iii.github.io  # the base hostname and protocol for your site, e.g. http://example.com